=== ARCOS-System/ARCOS/SampleDomains/BLEU/v5/BLEU_parts_v5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns:arcos="https://github.com/ARCOS-System/ARCOS/XSD"
           elementFormDefault="qualified"
           arcos:version="5">

  <xs:element name="Inventory">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Bolt" type="BoltType" maxOccurs="unbounded"/>
        <xs:element name="Nut" type="NutType" maxOccurs="unbounded"/>
        <xs:element name="Washer" type="WasherType" maxOccurs="unbounded"/>
        <xs:element name="Bracket" type="BracketType" maxOccurs="unbounded"/>
        <xs:element name="PackagedKit" type="PackagedKitType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="LocationType">
    <xs:attribute name="warehouse" type="xs:string"/>
    <xs:attribute name="section" type="xs:string"/>
    <xs:attribute name="shelf" type="xs:string"/>
    <xs:attribute name="bin" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="BaseItemType">
    <xs:sequence>
      <xs:element name="origin" type="CountryRefType"/>
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="Description" type="xs:string" minOccurs="0"/>
      <xs:element name="Location" type="LocationType"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="code" type="xs:string" use="required"/>
    <xs:attribute name="eco_cert" type="xs:string"/>
    <xs:attribute name="replacement" type="xs:boolean" default="false"/>
  </xs:complexType>

  <xs:complexType name="BoltType">
    <xs:complexContent>
      <xs:extension base="BaseItemType">
        <xs:sequence>
          <xs:element name="Length" type="xs:float"/>
          <xs:element name="Diameter" type="xs:float"/>
          <xs:element name="ThreadType" type="xs:string"/>
          <xs:element name="Material" type="xs:string"/>
          <xs:element name="HeadType" type="xs:string" minOccurs="0"/>
          <xs:element name="DriveType" type="xs:string" minOccurs="0"/>
          <xs:element name="Finish" type="xs:string" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="NutType">
    <xs:complexContent>
      <xs:extension base="BaseItemType">
        <xs:sequence>
          <xs:element name="Diameter" type="xs:float"/>
          <xs:element name="ThreadType" type="xs:string"/>
          <xs:element name="Height" type="xs:float"/>
          <xs:element name="Shape" type="xs:string"/>
          <xs:element name="Material" type="xs:string"/>
          <xs:element name="Finish" type="xs:string" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="WasherType">
    <xs:complexContent>
      <xs:extension base="BaseItemType">
        <xs:sequence>
          <xs:element name="InnerDiameter" type="xs:float"/>
          <xs:element name="OuterDiameter" type="xs:float"/>
          <xs:element name="Thickness" type="xs:float"/>
          <xs:element name="Material" type="xs:string"/>
          <xs:element name="Hardness" type="xs:string" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="BracketType">
    <xs:complexContent>
      <xs:extension base="BaseItemType">
        <xs:sequence>
          <xs:element name="Type" type="xs:string"/>
          <xs:element name="Width" type="xs:float"/>
          <xs:element name="Height" type="xs:float"/>
          <xs:element name="Thickness" type="xs:float"/>
          <xs:element name="HolePattern" type="xs:string"/>
          <xs:element name="Material" type="xs:string"/>
          <xs:element name="Finish" type="xs:string" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="PackagedKitType">
    <xs:sequence>
	  <xs:element name="AssemblyOrigin" type="CountryRefType"/>
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="Description" type="xs:string" minOccurs="0"/>
      <xs:element name="Components">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Component" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="ref" type="xs:IDREF" use="required"/>
                <xs:attribute name="quantity" type="xs:int" default="1"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="PackagingType" type="xs:string"/>
      <xs:element name="Dimensions">
        <xs:complexType>
          <xs:attribute name="length" type="xs:float"/>
          <xs:attribute name="width" type="xs:float"/>
          <xs:attribute name="height" type="xs:float"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Weight" type="xs:float"/>
      <xs:element name="Location" type="LocationType"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="code" type="xs:string" use="required"/>
  </xs:complexType>
  
	<xs:complexType name="CountryRefType">
	  <xs:sequence>
		<xs:element name="code" type="xs:string"/>
		<xs:element name="country" type="xs:string"/>
		<xs:element name="province" type="xs:string" minOccurs="0"/>
	  </xs:sequence>
	</xs:complexType>


</xs:schema>

=== ARCOS-System/ARCOS/SampleDomains/BLEU/v5/BLEU_inventory_v5_sample.xml
<?xml version='1.0' encoding='UTF-8'?>
<Inventory 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/ARCOS-System/ARCOS/refs/heads/main/SampleDomains/BLEU/v5/BLEU_parts_v5.xsd">

  <Bolt id="bolt001" code="BOLT-M12-40" eco_cert="FSC" replacement="true">
    <origin>
		<code>CA-QC</code>
		<country>Canada</country>
		<province>QC</province>
	</origin>
    <Name>M12 Bolt 40mm</Name>
    <Description>Zinc-plated bolt for structural use</Description>
    <Location warehouse="Main" section="A" shelf="1" bin="5"/>
    <Length>40</Length>
    <Diameter>12</Diameter>
    <ThreadType>Metric</ThreadType>
    <Material>Steel</Material>
    <HeadType>Hex</HeadType>
    <DriveType>External</DriveType>
    <Finish>Zinc</Finish>
  </Bolt>

  <Nut id="nut001" code="NUT-M12">
    <origin><code>CA-QC</code><country>Canada</country><province>QC</province></origin>
    <Name>M12 Hex Nut</Name>
    <Description>Hex nut for M12 bolts</Description>
    <Location warehouse="Main" section="A" shelf="1" bin="6"/>
    <Diameter>12</Diameter>
    <ThreadType>Metric</ThreadType>
    <Height>10</Height>
    <Shape>Hex</Shape>
    <Material>Steel</Material>
    <Finish>Zinc</Finish>
  </Nut>

  <Washer id="washer001" code="WASH-M12">
    <origin><code>CA-QC</code><country>Canada</country><province>QC</province></origin>
    <Name>M12 Washer</Name>
    <Description>Flat washer for M12 bolts</Description>
    <Location warehouse="Main" section="A" shelf="1" bin="7"/>
    <InnerDiameter>12</InnerDiameter>
    <OuterDiameter>24</OuterDiameter>
    <Thickness>2.5</Thickness>
    <Material>Steel</Material>
    <Hardness>Medium</Hardness>
  </Washer>

  <Bracket id="bracket001" code="BRK-L50">
    <origin><code>US-NY</code><country>United States</country><province>NY</province></origin>
    <Name>L-Bracket 50mm</Name>
    <Description>Angle bracket for mounting hardware</Description>
    <Location warehouse="Main" section="B" shelf="2" bin="1"/>
    <Type>L</Type>
    <Width>50</Width>
    <Height>50</Height>
    <Thickness>5</Thickness>
    <HolePattern>2xM12</HolePattern>
    <Material>Aluminum</Material>
    <Finish>Anodized</Finish>
  </Bracket>

  <PackagedKit id="kit001" code="KIT-M12-MOUNT">
    <AssemblyOrigin><code>CA-QC</code><country>Canada</country><province>Quebec</province></AssemblyOrigin>
    <Name>M12 Mounting Kit</Name>
    <Description>Includes M12 bolt, nut, and washer</Description>
    <Components>
      <Component ref="bolt001" quantity="1"/>
      <Component ref="nut001" quantity="1"/>
      <Component ref="washer001" quantity="1"/>
    </Components>
    <PackagingType>Bag</PackagingType>
    <Dimensions length="100" width="60" height="30"/>
    <Weight>150</Weight>
    <Location warehouse="Main" section="Kits" shelf="Top" bin="B1"/>
  </PackagedKit>
</Inventory>
